### ISSUE TITLE
Action does not trigger on my repo

### ISSUE THREAD

**Issue by kgashok** [sane-fmt/action#8]
https://github.com/kgashok/cyberdojo-exercises/blob/master/.github/workflows/jsformat.yml  

I have no idea why it doesn't do a PR with the changes?
Am I missing something?

**Comment by KSXGitHub** [comment]
> I have no idea why it doesn't do a PR with the changes?

Because it doesn't. I may implement this feature, but for now, it does only checking.

**Comment by kgashok** [comment]
Do you know of any other action that does this already?

**Comment by KSXGitHub** [comment]
[this one] commits directly to your repo.

**Comment by kgashok** [comment]
> [this one] commits directly to your repo.
Link is missing. Thanks,

**Comment by KSXGitHub** [comment]
updated

**Comment by kgashok** [comment]
Thanks much, @KSXGitHub !
